---
stages:
  - build

image: docker:19.03.8

services:
  - docker:19.03.8-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:ark-dedicated-server:latest:
  stage: build
  script:
    - echo "Shared runners do not have enough capacity to do actual builds with the game install."
    # - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    # - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # - docker push $CI_REGISTRY_IMAGE:latest
