---
version: "3.8"

services:
  server:
    build: .
    env_file:
      - .env
    volumes:
      - type: volume
        source: data
        target: /app/ark/dedicated-server/ShooterGame/Saved
    ports:
      - 27015:27015/udp
      - 27015:27015/tcp
      - 27020:27020/tcp
      - 7777:7777/udp
      - 7777:7777/tcp
      - 7778:7778/udp
      - 7778:7778/tcp

volumes:
  data: null
